server:
  port: 8892

#eureka.config
eureka:
  instance:
    hostname: node2
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://node1:8891/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0