server:
  port: 8891

#eureka.config
eureka:
  instance:
    hostname: node1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://node2:8892/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0